### ISSUE TITLE
role="math" styling?

### ISSUE THREAD

**Issue by tigt** [niksy/rationalize.css#15]
I've used this declaration in my blog CSS for a while:

```css
[role~="math"] {
  font-family: serif;
  speak-as: literal-punctuation;
}
```

The `font-family` is just to typographically offset the contents, but `speak-as` is helpful for VoiceOver users, as it's one of the few CSS3 Speech properties it supports. (It would be nice to set it on things like `a[href^="tel:"], a[href^="mailto:"]` as well, but you can't guarantee those don't contain text like "click here" or "call us anytime" instead of the actual addresses.)

The `~=` selector is used because the `role` attribute can take a space-separated list of roles, and uses the first one it recognizes. Just a little future-proofing, but it may not be necessary for your needs.
