### ISSUE TITLE
Improve subscript and superscript display

### ISSUE THREAD

**Issue by niksy** [niksy/rationalize.css#23]
Reference: https://alistapart.com/article/web-typography-numerals#section3

---

Example code:

```css
@supports ( font-variant-position: sub ) {
  sub { vertical-align: baseline;
        font-size: inherit;
        font-variant-position: sub; }
}

@supports ( font-variant-position: super ) {
  sup { vertical-align: baseline;
        font-size: inherit;
        font-variant-position: super; }
}
```
